[package]
name = "EstruturasDeDados2"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "encryption"
path = "benches/encryption_module_benchmark.rs"
harness = false
